[package]
name = "kms-health-check"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true
license.workspace = true
readme = "README.md"
# Inherited from repository root Cargo.toml

[dependencies]
anyhow.workspace = true
clap.workspace = true
config.workspace = true
hex.workspace = true
kms-grpc.workspace = true
kms.workspace = true
observability.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
validator.workspace = true
