[package]
name = "threshold-types"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true
license.workspace = true
# TODO(dp): write a proper description
description = "Types used across crates in 'threshold'"

[dependencies]
algebra.workspace = true
aes-prng.workspace = true
async-trait.workspace = true
anyhow.workspace = true
hashing.workspace = true
rand.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }

[dev-dependencies]

[features]
default = ["non-wasm"]

non-wasm = [
	"algebra/non-wasm",
	# "error-utils/non-wasm",

	# "dep:attestation-doc-validation",
	# "dep:hyper-rustls-ring",
 #    "dep:observability",
 #    "dep:thread-handles",
 #    "dep:tokio",
 #    "dep:x509-parser",
 #    "dep:tokio-rustls",
 #    "dep:tonic-tls",
]
testing = ["non-wasm"]
malicious_strategies = ["testing"]
choreographer = ["malicious_strategies"]
