# See default.toml for the documentation.

tick_interval_secs = 1

[blockchain]
addresses = ["http://localhost:9090"]
asc_address = "wasm1qwlgtx52gsdu7dtp0cekka5zehdl0uj3fhp9acg325fvgs8jdzksu3v4ff"
csc_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"

[blockchain.signkey]
mnemonic = "sugar vapor common surprise ice absorb exhaust blouse one lady remain give endorse ostrich wife occur cry veteran jungle catalog broken actual push evidence"

[blockchain.fee]
denom = "ucosm"
amount = 3000000

[sharding]
index = 0
total = 1

[core]
addresses = ["http://localhost:50051"]

[core.timeout_config]
channel_timeout = 60

[core.timeout_config.crs]
initial_wait_time = 60
retry_interval = 60
max_poll_count = 120

[core.timeout_config.insecure_crs]
initial_wait_time = 10
retry_interval = 10
max_poll_count = 200

[core.timeout_config.keygen]
initial_wait_time = 60
retry_interval = 15
max_poll_count = 10000

[core.timeout_config.preproc]
initial_wait_time = 60
retry_interval = 15
max_poll_count = 10000

[core.timeout_config.decryption]
initial_wait_time = 0
retry_interval = 3
max_poll_count = 100

[core.timeout_config.insecure_key_gen]
initial_wait_time = 10
retry_interval = 10
max_poll_count = 200

[core.timeout_config.reencryption]
initial_wait_time = 0
retry_interval = 3
max_poll_count = 100

[core.timeout_config.verify_proven_ct]
initial_wait_time = 1
retry_interval = 1
max_poll_count = 24

[tracing]
service_name = "kms-connector-2"
endpoint = "http://otelcol:4317"

[store]
url = "http://localhost:8088"
