# See default.toml for the documentation.

tick_interval_secs = 1

[blockchain]
addresses = ["http://localhost:9090"]
asc_address = "wasm1aakfpghcanxtc45gpqlx8j3rq0zcpyf49qmhm9mdjrfx036h4z5se0hfnq"
csc_address = "wasm14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9s0phg4d"

[blockchain.signkey]
mnemonic = "false since tiny tobacco help blame fade renew index tag crew cluster slim soul alone mail shove grab globe token private mushroom quote horse"

[blockchain.fee]
denom = "ucosm"
amount = 3000000

[sharding]
index = 0
total = 1

[core]
addresses = ["http://localhost:50051"]

[core.timeout_config]
channel_timeout = 60

[core.timeout_config.crs]
initial_wait_time = 60
retry_interval = 60
max_poll_count = 120

[core.timeout_config.insecure_crs]
initial_wait_time = 10
retry_interval = 10
max_poll_count = 200

[core.timeout_config.keygen]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 1150

[core.timeout_config.preproc]
initial_wait_time = 18000
retry_interval = 15000
max_poll_count = 1150

[core.timeout_config.decryption]
initial_wait_time = 0
retry_interval = 3
max_poll_count = 100

[core.timeout_config.insecure_key_gen]
initial_wait_time = 10
retry_interval = 10
max_poll_count = 200

[core.timeout_config.reencryption]
initial_wait_time = 0
retry_interval = 3
max_poll_count = 100

[core.timeout_config.verify_proven_ct]
initial_wait_time = 1
retry_interval = 1
max_poll_count = 24

[tracing]
service_name = "kms-connector-4"
endpoint = "http://otelcol:4317"

[store]
url = "http://localhost:8088"
