kmsGenKeys:
  enabled: true
  keyGenArgs: "insecure-key-gen"
  crsGenArgs: "insecure-crs-gen --max-num-bits 2048"
  configmap:
    name: kms-keys
  resources:
    requests:
      memory: 24Gi
      cpu: 4
    limits:
      memory: 24Gi
      cpu: 4

minio:
  enabled: true
  endpoint: "http://localstack:4566"
  username: kms-access-key-id
  password: kms-secret-access-key

kubeUtils:
  image:
    name: ghcr.io/zama-ai/security-hub/infra/kube-utils
    tag: v0.4.3
    pullPolicy: Always

kmsCore:
  enabled: false
  thresholdMode:
    enabled: true
    peersList:
      - id: 1
        host: kms-service-threshold-1-<namespace>-core-1
        port: 50001
      - id: 2
        host: kms-service-threshold-2-<namespace>-core-2
        port: 50001
      - id: 3
        host: kms-service-threshold-3-<namespace>-core-3
        port: 50001
      - id: 4
        host: kms-service-threshold-4-<namespace>-core-4
        port: 50001
      - id: 5
        host: kms-service-threshold-5-<namespace>-core-5
        port: 50001
      - id: 6
        host: kms-service-threshold-6-<namespace>-core-6
        port: 50001

kmsCoreClient:
  enabled: false
  image:
    name: ghcr.io/zama-ai/kms/core-client
    tag:
  num_majority: 2 # 2 when 4 parties and 5 when 13 parties
  num_reconstruct: 3 # 3 when 4 parties and 9 when 13 parties
  decryption_mode: NoiseFloodSmall
  fhe_parameter: Test

kmsInit:
  enabled: false

kmsGenCertAndKeys:
  enabled: false