kmsPeers:
  id: 3

kmsCore:
  serviceAccountName: kms-enclave-ci-3
  envFrom:
    configmap:
      name: kms-enclave-ci-3
  publicVault:
    s3:
      enabled: true
      prefix: PUB-p3
  privateVault:
    awskms:
      enabled: true
    s3:
      enabled: true
      prefix: PRIV-p3

kmsGenCertAndKeys:
  enabled: true
