kmsPeers:
  id: 11

kmsCore:
  serviceAccountName: kms-enclave-ci-11
  envFrom:
    configmap:
      name: kms-enclave-ci-11
  publicVault:
    s3:
      enabled: true
      prefix: PUB-p11
  privateVault:
    awskms:
      enabled: true
    s3:
      enabled: true
      prefix: PRIV-p11

kmsGenCertAndKeys:
  enabled: true
