kmsPeers:
  id: 9

kmsCore:
  serviceAccountName: kms-enclave-ci-9
  envFrom:
    configmap:
      name: kms-enclave-ci-9
  publicVault:
    s3:
      enabled: true
      prefix: PUB-p9
  privateVault:
    awskms:
      enabled: true
    s3:
      enabled: true
      prefix: PRIV-p9

kmsGenCertAndKeys:
  enabled: true
