kmsPeers:
  id: 5

kmsCore:
  serviceAccountName: kms-enclave-ci-5
  envFrom:
    configmap:
      name: kms-enclave-ci-5
  publicVault:
    s3:
      enabled: true
      prefix: PUB-p5
  privateVault:
    awskms:
      enabled: true
    s3:
      enabled: true
      prefix: PRIV-p5

kmsGenCertAndKeys:
  enabled: true
