kmsPeers:
  id: 12

kmsCore:
  serviceAccountName: kms-ci-12
  envFrom:
    configmap:
      name: kms-ci-12
  publicVault:
    s3:
      enabled: true
      prefix: PUB-p12
  privateVault:
    awskms:
      enabled: true
    s3:
      enabled: true
      prefix: PRIV-p12

kmsGenCertAndKeys:
  enabled: false