kmsPeers:
  id: 10

kmsCore:
  serviceAccountName: kms-ci-10
  envFrom:
    configmap:
      name: kms-ci-10
  publicVault:
    s3:
      enabled: true
      prefix: PUB-p10
  privateVault:
    awskms:
      enabled: true
    s3:
      enabled: true
      prefix: PRIV-p10

kmsGenCertAndKeys:
  enabled: false