kmsPeers:
  id: 8

kmsCore:
  serviceAccountName: kms-ci-8
  envFrom:
    configmap:
      name: kms-ci-8
  publicVault:
    s3:
      enabled: true
      prefix: PUB-p8
  privateVault:
    awskms:
      enabled: true
    s3:
      enabled: true
      prefix: PRIV-p8

kmsGenCertAndKeys:
  enabled: false