kmsPeers:
  id: 7

kmsCore:
  serviceAccountName: kms-ci-7
  envFrom:
    configmap:
      name: kms-ci-7
  publicVault:
    s3:
      enabled: true
      prefix: PUB-p7
  privateVault:
    awskms:
      enabled: true
    s3:
      enabled: true
      prefix: PRIV-p7

kmsGenCertAndKeys:
  enabled: false