[package]
name = "error-utils"
version.workspace   = true
edition.workspace   = true
license.workspace   = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true

[dev-dependencies]
tracing-test.workspace = true

[features]
non-wasm = []
