[package]
name = "threshold-hashing"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true
license.workspace = true
description = "Hashing utilities"

[dependencies]
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
sha3.workspace = true
bc2wrap.workspace = true
