kmsPeers:
  # Number of replicas managed by each statefulset
  count: 1

kmsConnector:
  enabled: false

kmsCore:
  nameOverride:
  addressOverride:
  image:
    name: ghcr.io/zama-ai/kms/core-service-enclave
    tag: <version>
  thresholdMode:
    enabled: false
  aws:
    region: eu-west-1
  storage:
    storageClassName: gp3
    capacity: 5Gi
  serviceMonitor:
    enabled: false
  resources:
    requests:
      memory: 4Gi
      cpu: 2
    limits:
      memory: 10Gi
      ephemeralStorage: 1Gi
      grpcTimeout: 360
      grpcMaxMessageSize: 2097520

  nitroEnclave:
    enabled: true
    cpuCount: 48
    memoryGiB: 96

  tolerations:
    - key: app
      effect: NoSchedule
      operator: Equal
      value: kms-enclave-ci

mtls:
  enabled: false

environment: dev

tracing:
  enabled: false
  endpoint: "http://otel-deployment-opentelemetry-collector.observability.svc.cluster.local:4317"
  metrics:
    enabled: false
    interval_sec: 20

socat:
  image:
    name: alpine/socat
    tag: latest

rustLog: info

minio:
  enabled: false
